### ISSUE TITLE
А если без кастинга просто закинуть аргумент? Не работает?

### ISSUE THREAD

**Issue by coursar** [jed116/di-reflect-lib#3]
https://github.com/jed116/di-reflect-lib/blob/0a5799d166b8663924698b410d6b68da11aa469d/src/main/java/tech/itpark/container/Container.java#L16-L38

**Comment by jed116** [comment]
Валится эксепшн "java.lang.IllegalArgumentException: argument type mismatch" если в definitions.json присутствует числовой аргумент в массиве параметров
